### ISSUE TITLE
xpmem kernel fails to build on debian and SLES due to kernel headers location

### ISSUE THREAD

**Issue by tzafrir-mellanox** [openucx/xpmem#25]
Recent master, ./configure && (cd kernel && make)

/labhome/tzafrirc/sysgwork/ofed/xpmem/xpmem/kernel/xpmem_pfn.c: In function 'xpmem_pin_page':
/labhome/tzafrirc/sysgwork/ofed/xpmem/xpmem/kernel/xpmem_pfn.c:265:25: error: 'struct task_struct' has no member named 'cpus_allowed'; did you mean 'nr_cpus_allowed'?
  265 |   saved_mask = current->cpus_allowed;
      |                         ^~~~~~~~~~~~
      |                         nr_cpus_allowed

If I manually edit config.h to define HAVE_STRUCT_TASK_STRUCT_CPUS_MASK , this works OK, but continues to fail on an error with PDE.

So why does it fail? On config.log I see:
configure:12967: gcc -c -g -O2 -include /lib/modules/5.10.0-13-amd64/build//include/linux/kconfig.h             -include /lib/modules/5.10.0-13-amd64/build//include/linux/compiler.h             -D__KERNEL__             -I/lib/modules/5.10.0-13-amd64/build//include             -I/lib/modules/5.10.0-13-amd64/build//include/uapi             -I/lib/modules/5.10.0-13-amd64/build//arch/x86/include             -I/lib/modules/5.10.0-13-amd64/build//arch/x86/include/uapi             -I/lib/modules/5.10.0-13-amd64/build//arch/x86/include/generated             -I/lib/modules/5.10.0-13-amd64/build//arch/x86/include/generated/uapi              conftest.c >&5
cc1: fatal error: /lib/modules/5.10.0-13-amd64/build//include/linux/kconfig.h: No such file or directory
compilation terminated.                                                         

And indeed /lib/modules/5.10.0-13-amd64/build//include/linux/kconfig.h is not there. So how does kernel build work?

$ cat /lib/modules/5.10.0-13-amd64/build/Makefile 
include /usr/src/linux-headers-5.10.0-13-common/Makefile

I also see:
$ ls -l /lib/modules/5.10.0-13-amd64/ | grep -- '->'
lrwxrwxrwx  1 root root      38 Mar 17  2022 build -> /usr/src/linux-headers-5.10.0-13-amd64
lrwxrwxrwx  1 root root      39 Mar 17  2022 source -> /usr/src/linux-headers-5.10.0-13-common

and /lib/modules/5.10.0-13-amd64/source/include/linux/kconfig.h is the right file.

**Comment by tzafrir-mellanox** [comment]
This also seems to be the case with SLES12 and SLES15 kernels.

**Comment by davidecarlson** [comment]
I'm seeing similar issues on Rocky Linux 8.5

**Comment by tzafrir-mellanox** [comment]
Are you sure it's the same issue? My workaround / fix is along the lines of PR #26 (with a test for more lines). This is not the case on Centos kernels, AFAIK. Are you sure you have kernels?

**Comment by tvegas1** [comment]
Where do we stand with one?
